
title: Second Draft
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.


# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

#others
excerpt_separator: <!--more-->

text1: It's not the emotion you experience that help form habits, but the competence and clarity you develop in performing the behavior. That sense of capability produces a feeling of success, which reinforces the desire to repeat it.
text2: Using analogies in explanation to make complex ideas more intelligible to reader can be misleading if they are taken as actual explanations, and they can distort the deeper truth. They often give the impression that we understand something when we don’t truly grasp its essence.
text3: 
text4: ☃︎
